name: flutter_tflite_ffi_example
description: Demonstrates how to use the flutter_tflite_ffi plugin.
publish_to: none
version: "0.0.0+0"

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_tflite_ffi:
    path: ../
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mobilenet_v1_quant.tflite
    - assets/labels.txt
    - assets/test_image.jpg
